added pre-commit, CI and made sure everything passed
mantidproject/quasielasticbayes pull request #15
Opened 2022-08-04 14:56 UTC by AnthonyLim23

This PR adds pre-commit checks, CI tests (excluding mac, but I did include the dev file so we can come back to it later), updating the tests to pass and updating the docs.

2022-08-04 15:00 UTC, AnthonyLim23 commented
@martyngigg this is ready for review when you have some time

2022-08-10 13:36 UTC, AnthonyLim23 commented
I have had a look at the pre-commit and stuff. The script seems to be generated from latest version on my laptop (the one that works). However, I am unable to get pre-commit to run on my desktop (got the correct script now).

2022-08-10 14:13 UTC, AnthonyLim23 commented on README.md
> +To activate pre-commit, setup the Conda environment and then type ``pre-commit install`` into your terminal (Git bash on Windows).
```suggestion
To activate pre-commit, setup the Conda environment and then type ``mamba pre-commit update``.
Then once its updated type ``pre-commit install``, this generates a bash style file.
However, this will produce an error when you try to run it (a known issue with pre-commit).
In your terminal type `` mamba env update --file quasielasticbayes-dev-win.yml --prune``
Once it has completed, close the terminal and open a new one and activate the Conda environment.
In your terminal (Gitbash on Windows) you will now be able to run pre-commit checks (outside of your Conda environment). 
```

2022-08-10 14:55 UTC, martyngigg requested changes
Thanks for getting the code to this stage. It's a good start to making this something more maintainable.

I've got a few minor inline comments of things to tidy up.

I also can't comment on the `.7z` file directly but can we move it to something like a `tools/vendored/mingw` directory and add a README to the directory with a short explanation of why its here and where it came from? Would it also be possible to change the filename so it contains the version number?

2022-08-10 14:55 UTC, martyngigg commented on .github/workflows/flake8.yml
> +    - 'release-*'
Can we remove the `release-*` from these configurations? As we don't have it yet and it's not completely clear if we will need it yet then it would be good to keep it the files referencing things that currently exist.

2022-08-10 14:55 UTC, martyngigg commented on .github/workflows/run_tests.yml
> +                 echo "hi"
Can we remove this debugging code?

2022-08-10 14:55 UTC, martyngigg commented on .github/workflows/run_tests.yml
> +            python -m pip install -v --editable .
Do we need the `--editible` flag here? That just ensures that we can still change the Python files during development without having to run `pip install` each time. Running without `--editable` will also ensure the tests work against a proper packaged version.

2022-08-10 14:55 UTC, martyngigg commented on .pre-commit-config.yaml
> +  skip: [clang-format]
Can we remove this? It only applies to the `mantid` workflow.

2022-08-10 14:55 UTC, martyngigg commented on .pre-commit-config.yaml
> +  #exclude: ^$|instrument/
I don't think this is applicable here? Can we remove it?

2022-08-10 14:55 UTC, martyngigg commented on quasielasticbayes-dev-linux.yml
>    - python=3.6.*
Once this is merged can we create an issue to update to Python 3.8? As mantid has moved to that we will need to do that too.

2022-08-10 14:55 UTC, martyngigg commented on quasielasticbayes-dev-win.yml
> +  - m2w64-gcc-libgfortran==5.3.0
Do we need this if we are using our zipped version of mingw for now?

2022-08-10 14:55 UTC, martyngigg commented on quasielasticbayes/__init__.py
> -from . import QLdata, QLres, ResNorm, QLse
I think this is a good idea so that we only import what we need but will this be a breaking change for Mantid?

2022-08-10 14:57 UTC, AnthonyLim23 commented on .github/workflows/run_tests.yml
> +                 echo "hi"
thought I got that. Thanks for spotting it

2022-08-10 14:58 UTC, AnthonyLim23 commented on .github/workflows/run_tests.yml
> +            python -m pip install -v --editable .
Sure, I just copied what it said in the readme

2022-08-10 14:59 UTC, AnthonyLim23 commented on quasielasticbayes/__init__.py
> -from . import QLdata, QLres, ResNorm, QLse
Honestly, I do not know. I can put it back if we are unsure

2022-08-10 15:09 UTC, AnthonyLim23 commented on quasielasticbayes-dev-linux.yml
>    - python=3.6.*
https://github.com/mantidproject/quasielasticbayes/issues/17

2022-08-10 15:10 UTC, martyngigg commented on quasielasticbayes/__init__.py
> -from . import QLdata, QLres, ResNorm, QLse
I think it would be better without but maybe we put this back for now and create an issue as there are a lot of changes in here already?

2022-08-10 15:57 UTC, martyngigg commented on .github/workflows/label_merge_conflicts.yml
> +      #- 'release-next'
Just one more `release-` reference...

2022-08-10 15:58 UTC, martyngigg commented on README.md
> +- Download MinGW64.7z and unzip it into ``C:\MinGW64``
Do we need to update this now we have moved the file?

2022-08-19 14:07 UTC, AnthonyLim23 commented
@martyngigg it should be ready for another review

2022-08-24 12:12 UTC, martyngigg approved these changes
This is looking to be in good shape now.

Just one question that I won't hold up the approval for.

2022-08-24 12:12 UTC, martyngigg commented on setup.py
> -    return [str(dirname / filename) for filename in filenames]
I'm not going to hold this up for this but can I ask the reason for switching from a `Path` type to a `str`?

2022-08-24 12:14 UTC, merged

2022-08-24 12:19 UTC, AnthonyLim23 commented on setup.py
> -    return [str(dirname / filename) for filename in filenames]
I found it easier to work with when coupled with os.path