Cython and Fortran together
mantidproject/quasielasticbayes pull request #19
Opened 2022-09-06 12:43 UTC by AnthonyLim23

2022-09-06 15:20 UTC, AnthonyLim23 commented on quasielasticbayes-dev-linux.yml
> +  - python #=3.6.*
I had to remove this pin to get the cython to compile on Linux. Otherwise it was unable to find some libs.

2022-09-08 07:44 UTC, martyngigg requested changes

2022-09-08 07:44 UTC, martyngigg commented on setup.py
> +from cython_setup import get_cython_extensions
I like the clarity of the separation of the Cython & Fortran setup.

2022-09-08 07:44 UTC, martyngigg commented on quasielasticbayes-dev-linux.yml
> +     - cython>=0.29.32 # needed due to conda getting the wrong version
I suspect the old 3.6 pinning was giving you an older version here. You may now find that with the 3.8 pinning you will get the correct latest version of Cython.

2022-09-08 07:44 UTC, martyngigg commented on src/c_python/bayes_C.pyx
> +# Mantid Repository : https://github.com/mantidproject/mantid
Can I ask the relation of this `c_python` folder to the current `quasielasticbayes` folder? I don't quite follow what the final package structure will be.

2022-09-08 07:44 UTC, martyngigg commented on src/c_python/constants.py
> +m_d = 4096
I assume for the translation that keeping the variable names the same was the intent to avoid translation errors? Could we have some comments on them though?

2022-09-08 07:44 UTC, martyngigg commented on src/c_python/data.py
> +from quasielasticbayes.fortran_python import vec, matrix_2, c_vec, c_matrix_2
Could we add more comments and docstrings for classes and methods so that they describe their intent?

2022-09-08 07:44 UTC, martyngigg commented on src/c_python/fortran_python.pyx
> +class vec(object):
Can all class names be capitalized or please leave a comment as to why that is not the case.

2022-09-08 07:44 UTC, martyngigg commented on src/c_python/fortran_python.pyx
> +class matrix_2(vec):
Are the names from the fortran? If not is there a more descriptive name than `matrix_2` we could use?

2022-09-08 07:44 UTC, martyngigg commented on src/c_python/fortran_python.pyx
> +"""
Good docstring on describing the intent. Can we move it just under the `class storage(object)` line. It will then appear attached to the `class.__doc__` attribute.

2022-09-08 07:44 UTC, martyngigg commented on test/data/FFT_test.tx
> +  9.76562151E-04
I've not come across the `.tx` extension before - is it a Cython-related thing?

2022-09-08 08:34 UTC, AnthonyLim23 commented on src/c_python/bayes_C.pyx
> +# Mantid Repository : https://github.com/mantidproject/mantid
I wanted to put the python files in a different folder to the fortran, so needed a different name. Since python and cython are both names I am unable to use (confuses the setup tools) I settled on c_python. I can change name if you can think of a better name

2022-09-08 08:34 UTC, AnthonyLim23 commented on src/c_python/constants.py
> +m_d = 4096
yes.

2022-09-08 08:35 UTC, AnthonyLim23 commented on src/c_python/fortran_python.pyx
> +class matrix_2(vec):
the 2 represents the dimensionality of the matrix. could change it to D2 (and D3)

2022-09-08 08:35 UTC, AnthonyLim23 commented on test/data/FFT_test.tx
> +  9.76562151E-04
it was a fortran issue. When I wrote out the data it cut off the final t from the ".txt"

2022-09-08 08:36 UTC, AnthonyLim23 commented
I am going to continue uploading the rest of the files and making sure that everything passes. Once I have done that I will make the changes (then I know that I havent broken it)

2022-09-08 10:32 UTC, martyngigg commented on src/c_python/fortran_python.pyx
> +class matrix_2(vec):
Yes I think something like that would be useful.

2022-09-08 10:52 UTC, martyngigg commented on src/c_python/bayes_C.pyx
> +# Mantid Repository : https://github.com/mantidproject/mantid
I guess I don't quite follow why we need to do that? I thought the intention was to have the internals of `quasielasticbayes` be switched to the new python/cython combination that replaces the current fortran?

Both implementations could be left accessible if we did something like

```python
src/
|- quasielasticbayes/
   |- legacy_fortran/
      |- __init__.py
      |- Bayes.f90
      |- Four.f90
      |- ...
   |- c_python/
      |- __init__.py
      |- ...
   |- __init__.py
```

Then the top-level `__init__.py`  can select between the implementations easily:
```
from .legacy_fortran import QLdata # + the others that are there.
```
would keep using the old fortran.

If we want to given Spencer a version to test we can then create a version that has

```python
from .c_python import QLdata # + the others that are there.
```
and it would use your new Cython implementation.

Or have I misunderstood the intention here?

2022-09-08 11:37 UTC, AnthonyLim23 commented on src/c_python/bayes_C.pyx
> +# Mantid Repository : https://github.com/mantidproject/mantid
that would work. Except, the setup file will automatically pick up all of the modules, which need to have unique names (case insensitive)

2022-09-08 12:44 UTC, martyngigg commented on src/c_python/bayes_C.pyx
> +# Mantid Repository : https://github.com/mantidproject/mantid
Can you help me understand why the names need to be unique if they are in subpackages? Setuptools can deal with qualified names in Extension [definitions](https://setuptools.pypa.io/en/stable/deprecated/distutils/setupscript.html?highlight=ext_modules#extension-names-and-packages).

2022-09-08 12:47 UTC, AnthonyLim23 commented on src/c_python/bayes_C.pyx
> +# Mantid Repository : https://github.com/mantidproject/mantid
I never looked into the why, but when I had `Four` (from the fortran) and then `four` from Cython, the cython instance replaced the fortran (because cython was compiled second)

2022-09-14 09:09 UTC, AnthonyLim23 commented
Everything is uploaded now. I will start cleaning up the code (there a few things I want to do).

2022-09-14 10:10 UTC, martyngigg commented on cython_setup.py
> +        f'{PACKAGE_NAME}.constants':
If this `package_name` variable was called `quasielasticbayes.c_python` would this make the internal subpackages work? I think this might be why the files are clashing.

2022-09-14 10:22 UTC, AnthonyLim23 commented on cython_setup.py
> +        f'{PACKAGE_NAME}.constants':
Its possible, I don't know. 

I am currently cleaning up the code (deleting dead code and making sure I dont call any deprecated code). Once that is done I will try it.

I also want to try making an options module that will determine if we run python or fortran. Then we could wrap all of the calls and the API is the same with just an option being set before hand.

2022-10-12 14:28 UTC, AnthonyLim23 commented
I think this is ready to review. 

I have made an extra change, by deleting the individual yml files for conda. I wanted to be able to see the differences between the OS's easily on a single screen. So it is now generated by a python script. 

I have not added "c_python" and "fortran" to the names of the modules (e.g. quasielasticbayes.c_python.four or quasielasticbayes.fortran.four). I think it is better to do it as part of https://github.com/mantidproject/quasielasticbayes/issues/29 so we do not change the current API.

2022-10-17 16:36 UTC, martyngigg reviewed
Can we move the scripts for the yml file creation to a subdirectory such as `tools` or something. It's good to try and avoid dumping everything in the top directory.

2022-10-17 16:36 UTC, martyngigg commented on conda_dict_to_yml.py
> +Written a custom passer to write yml file
When you say the default here, do you mean the `PyYAML` package?

2022-10-17 16:36 UTC, martyngigg commented on README.md
> +> python yml_file_from_python u
I like the generation of the `yml` files from a single source but I can't see this `yml_file_from_python` file anywhere? Is the `u` a typo here or an argument, if it's an argument can we use something more descriptive?

2022-10-17 16:36 UTC, martyngigg commented on README.md
> +> python yml_file_from_python w
Where does the `python` command come from here if we have not yet activated a conda environment?

2022-10-17 16:36 UTC, martyngigg commented on conda_dict_to_yml.py
> +Written a custom passer to write yml file
Please can you add function doc strings and type annotations to all of the argument names. It's a good practice to do this everywhere and it will become second nature.

2022-10-17 16:36 UTC, martyngigg commented on test/stuff_test.py
> +"""Characterization tests for QLres module"""
Can we use a more descriptive name that `stuff` or was this a test that was committed that we no longer need?

2022-10-17 16:36 UTC, martyngigg commented on test/four_python_test.py
> +from quasielasticbayes.Four import four
I'm a little confused at the source package structure and how this is importable? `Four` is in the `legacy_fortran` subpackage but somehow ends up at the top level in the built package?

Do all of the built files currently end up at the top level?

2022-10-18 09:12 UTC, AnthonyLim23 commented on conda_dict_to_yml.py
> +Written a custom passer to write yml file
When I say default, I mean it is the set of packages that will be installed if we dont overwrite/add anything specific for that OS.

2022-10-18 09:13 UTC, AnthonyLim23 commented on README.md
> +> python yml_file_from_python u
u is a shorthand for ubuntu-latest, w for windows-latest and m for macOS-latest. I can change it to ubuntu, windows and mac

2022-10-18 09:14 UTC, AnthonyLim23 commented on README.md
> +> python yml_file_from_python w
that step does require the user to have a python package installed on their default system. It comes pre-installed on the github action machines and I think most users will have python somewhere.

2022-10-18 09:15 UTC, AnthonyLim23 commented on test/stuff_test.py
> +"""Characterization tests for QLres module"""
this shouldnt be here. It was a test for the cython build

2022-10-18 09:22 UTC, AnthonyLim23 commented on test/four_python_test.py
> +from quasielasticbayes.Four import four
The location within the package structure is determined in the setup file (e.g. https://github.com/mantidproject/quasielasticbayes/pull/19/files/89e20913f9a7c89fb110376f2980275f7a7513db#diff-521a6d26b973d62e7cb6d040d6911e4dad78143567d206de217e129829226c76R86). My plan is to leave everything at the top level for the beta version (no changes to the API) and to then move everything in https://github.com/mantidproject/quasielasticbayes/issues/29 which will be done for the main release at the end of the year.

2022-10-18 10:26 UTC, martyngigg commented on test/four_python_test.py
> +from quasielasticbayes.Four import four
Okay. It would be good to get the new structure in place as soon as possible to allow it to bed in and there be less confusion between what the source code looks like and the final product.

If needs be we can always put imports in the top-level `__init__.py` that pulls the old api into the top-level so the public API stays the same.

2022-10-18 10:28 UTC, martyngigg commented on README.md
> +> python yml_file_from_python u
Yes please. I don't think this will be run frequently enough that typing it out will be an issue?

2022-10-18 10:29 UTC, martyngigg commented on README.md
> +> python yml_file_from_python w
I don't have on a default Python 3 on my mac and Windows won't come with one out of the box.

Another way of doing this be to just use these script to generate the `yaml` environment files and then commit those? That way developers will still see the regular `.yml` files?

2022-10-18 10:55 UTC, AnthonyLim23 commented on README.md
> +> python yml_file_from_python u
it was when I was developing it (lots of testing for the formatting). I will change it this afternoon

2022-10-18 10:56 UTC, AnthonyLim23 commented on README.md
> +> python yml_file_from_python w
yes we could do that. I would recommend leaving it as being generated in the tests

2022-10-18 10:56 UTC, AnthonyLim23 commented on test/four_python_test.py
> +from quasielasticbayes.Four import four
It is the next thing on my to do list once this PR goes in

2022-10-18 12:39 UTC, martyngigg commented on README.md
> +> python yml_file_from_python w
We should also consider the developer as the first-class citizen here and what it looks like from their perspective but it's not worth holding this up for.

2022-10-18 12:42 UTC, martyngigg commented on tools/conda_dict_to_yml.py
> +    """
I'm keen we get this in to get the beta ready but if you haven't got one already then please make an issue to add type annotations to all of the Python code. I would like to make it mandatory in the future.

2022-10-18 12:44 UTC, martyngigg approved these changes
I think we ready to get this initial version in so we can get a beta out to test. 👍🏻

2022-10-18 12:46 UTC, merged