Version 2 for QlData
mantidproject/quasielasticbayes pull request #38
Opened 2022-11-09 10:19 UTC by AnthonyLim23

This PR creates an easier to understand version for QlData using Python. The new code is much faster than the Python translation and easier to understand. 

For this version we do not report errors for the fit parameters, they will be added as part of #37

2022-11-09 14:10 UTC, AnthonyLim23 commented
I just realised that I had made a mistake in the log likelihood calculation. starting with the equation 4.20 page 88 and taking the logs:

sum_{j=1}{N} j + N*log(4 pi) - 0.5*chi^2 *log(exp(1)) - N*log(beta) - 0.5*log(det(Hess))

where beta is:
A_max*(x_max - x_min) eq. 4.17 page 87.

The original fortran seems to cancel out our beta term in https://github.com/mantidproject/quasielasticbayes/blob/main/src/quasielasticbayes/legacy_fortran/Bayes.f90#L320 and https://github.com/mantidproject/quasielasticbayes/blob/main/src/quasielasticbayes/legacy_fortran/Bayes.f90#L318
which is wrong as the term is not just a scale factor (therefore cannot be cancelled out)

2022-11-10 14:33 UTC, martyngigg requested changes
I like the look of the version 2 layout as it's far more obvious what each piece does and the comprehensive set of tests for the fit functions and fit engines is a good base to start as we mean to go on.

I've made a few inline code comments to consider.

2022-11-10 14:33 UTC, martyngigg commented on src/quasielasticbayes/v2_python/fit_functions/base.py
> +class BaseFitFunction(object):
Maybe define this as an abstract class so that it can't be instantiated? https://docs.python.org/3/library/abc.html#abc.abstractmethod

2022-11-10 14:33 UTC, martyngigg commented on src/quasielasticbayes/v2_python/fit_functions/base.py
> +    def report(self):
Maybe implement `__str__` instead or in addition to this so you can just do `str(function_object)` like you might with other Python objects and you've done with `__call__` to allow calling to work?

2022-11-10 14:33 UTC, martyngigg commented on src/quasielasticbayes/v2_python/fit_engines/scipy_fit.py
> +                    func: BaseFitFunction,
Could the `func` type be relaxed to `func: Callable` (it can be imported form `typing`)?

2022-11-10 14:33 UTC, martyngigg commented on src/quasielasticbayes/v2_python/fit_engines/scipy_fit.py
> +                              maxfev=220000,
Maybe define this as a global at module name with a slightly more descriptive name?

2022-11-10 14:38 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/fit_functions/base.py
> +    def report(self):
later the way report works is that it takes arguments that include a dict or results, so that it can append to the list (see https://github.com/mantidproject/quasielasticbayes/pull/38/files#diff-a73fa3db979be79718f4e387cbb0afe7e85a2c0160ca831ffcfcb94e14a29fdeR55) this is nice functionality because it allows us to easily call the qldata method multiple times for different Q values and we can then get the list of values easily. I don't think we could do that with the  `__str__` option

2022-11-10 14:39 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/fit_engines/scipy_fit.py
> +                    func: BaseFitFunction,
yeah, I see no reason why not

2022-11-10 14:40 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/fit_engines/scipy_fit.py
> +                              maxfev=220000,
do you mean the `maxfev` values? This is the maximum iterations keyword for curve fit. I can create a variable above and use that.

2022-11-10 16:10 UTC, martyngigg commented on src/quasielasticbayes/v2_python/fit_functions/base.py
> +    def _add_to_report(self, name: str, value: float,
I would make this a `@staticmethod` as it doesn't access or need access to any instance variables.

2022-11-10 16:10 UTC, martyngigg commented on src/quasielasticbayes/v2_python/fit_functions/base.py
> +    def report(self):
Ah I see it's not just a string representation it's accumulating as you go. I think adding types to these functions will help show that too and maybe some method strings to describe their purpose.

2022-11-10 16:10 UTC, martyngigg commented on src/quasielasticbayes/v2_python/fit_functions/base.py
> +        if name not in report_dict.keys():
Just for information. The [dict.setdefault](https://docs.python.org/3/library/stdtypes.html#dict.setdefault) is useful for this type of common use case of dictionaries:
```
param_results = report_dict.setdefault(name, [])
param_results.append(value)
return report_dict
```

2022-11-10 16:38 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/fit_functions/base.py
> +        if name not in report_dict.keys():
I changed a few of the base class argument lists to reflect how they are used in anger

2022-11-11 08:36 UTC, martyngigg approved these changes
I think this looks good to go now 👍🏻

2022-11-11 08:36 UTC, merged