Adding QSE
mantidproject/quasielasticbayes pull request #39
Opened 2022-11-14 11:44 UTC by AnthonyLim23

Currently a draft, want to check it passes tests and then refactor common code from qldata and qse fit functions

2022-11-16 08:31 UTC, martyngigg requested changes
This looks good and follows the same pattern as done for `qldata`.  I think it would be good to provide a link to the mantid source of the StretchedExp function but that's it really.

2022-11-16 08:31 UTC, martyngigg commented on src/quasielasticbayes/v2_python/fit_functions/delta_function.py
> +    def amplitude(self) -> str:
I like the addition of these properties to avoid needing to deal with the internal naming. 👍🏻

2022-11-16 08:31 UTC, martyngigg commented on src/quasielasticbayes/v2_python/fit_functions/stretch_exp.py
> +Mantid.
Maybe provide a link?

2022-11-16 10:52 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/fit_functions/stretch_exp.py
> +Mantid.
a link to Mantid or the file I have taken it from?

2022-11-16 10:53 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/fit_functions/stretch_exp.py
> +Mantid.
```suggestion
Mantid.
https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/plugins/functions/StretchedExpFTHelper.py
```

2022-11-17 10:19 UTC, martyngigg approved these changes
Thanks for making the updates.

2022-11-17 10:19 UTC, merged