44 muon
mantidproject/quasielasticbayes pull request #49
Opened 2023-02-09 15:25 UTC by AnthonyLim23

2023-02-17 17:47 UTC, MialLewis commented
Not directly related to the code, and may be user error, but I've been playing around with the attached script and have the following observations
[QuasiBayesMuon_3.txt](https://github.com/mantidproject/quasielasticbayes/files/10769396/QuasiBayesMuon_3.txt).

1.  Looking at the script output with `N=3` and `N=4` on line `66`, the `loglikelihood` does not indicate the correct value of N. This does not change when increase the number of MEvents through the `stats` variable on line `67`.
2. The script crashed several times with:
`Traceback (most recent call last):
  File "C:\Repos\GitHub\Working Files\QuasiBayes Muon check\QuasiBayesMuon_2.py", line 77, in <module>
    (params, errors, new_x, fits, errors_fit) = muon_expdecay_main(sample,BG_type, start, end, params, errors)
  File "src\quasielasticbayes\v2_python\muon_exp_decay_main.py", line 72, in quasielasticbayes.v2.MuonExpDecay.muon_expdecay_main
    results[prob_name] = [loglikelihood(len(sy), chi2,
  File "src\quasielasticbayes\v2_python\log_likelihood.py", line 51, in quasielasticbayes.v2.log_likelihood.loglikelihood
    log_hess_det = log10_hessian_det(covar)
  File "src\quasielasticbayes\v2_python\fit_engines\fit_utils.py", line 18, in quasielasticbayes.v2.fitting.fit_utils.log10_hessian_det
    hessian = np.linalg.inv(covar)
  File "C:\Users\wym92549\AppData\Local\mambaforge\envs\quasielasticbayes-dev\lib\site-packages\numpy\linalg\linalg.py", line 551, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "C:\Users\wym92549\AppData\Local\mambaforge\envs\quasielasticbayes-dev\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix`

2023-02-17 17:53 UTC, MialLewis requested changes
Code looks good overall, just a few queries to satisfy

2023-02-17 17:53 UTC, MialLewis commented on test/muonexpdecay_test.py
> +    def test_two_decays(self):
This test gives a runtime warning "invalid value encountered in sqrt" when running `muon_expdecay_main`

2023-02-17 19:44 UTC, AnthonyLim23 commented on test/muonexpdecay_test.py
> +        expected = results['N2:loglikelihood'][0]
yes

2023-02-17 19:44 UTC, AnthonyLim23 commented on test/muonexpdecay_test.py
> +    def test_two_decays(self):
I thought I fixed that. It is probably just the date. To clarify, its the 2 decays test?

2023-02-17 19:47 UTC, AnthonyLim23 commented
> Not directly related to the code, and may be user error, but I've been playing around with the attached script and have the following observations [QuasiBayesMuon_3.txt](https://github.com/mantidproject/quasielasticbayes/files/10769396/QuasiBayesMuon_3.txt).
> 
> 1. Looking at the script output with `N=3` and `N=4` on line `66`, the `loglikelihood` does not indicate the correct value of N. This does not change when increase the number of MEvents through the `stats` variable on line `67`.
> 2. The script crashed several times with 'N=2' and 'stats>100', though I can't replicate currently...:
>    `Traceback (most recent call last):   File "C:\Repos\GitHub\Working Files\QuasiBayes Muon check\QuasiBayesMuon_2.py", line 77, in <module> (params, errors, new_x, fits, errors_fit) = muon_expdecay_main(sample,BG_type, start, end, params, errors)   File "src\quasielasticbayes\v2_python\muon_exp_decay_main.py", line 72, in quasielasticbayes.v2.MuonExpDecay.muon_expdecay_main results[prob_name] = [loglikelihood(len(sy), chi2,   File "src\quasielasticbayes\v2_python\log_likelihood.py", line 51, in quasielasticbayes.v2.log_likelihood.loglikelihood log_hess_det = log10_hessian_det(covar)   File "src\quasielasticbayes\v2_python\fit_engines\fit_utils.py", line 18, in quasielasticbayes.v2.fitting.fit_utils.log10_hessian_det hessian = np.linalg.inv(covar)   File "C:\Users\wym92549\AppData\Local\mambaforge\envs\quasielasticbayes-dev\lib\site-packages\numpy\linalg\linalg.py", line 551, in inv ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)   File "C:\Users\wym92549\AppData\Local\mambaforge\envs\quasielasticbayes-dev\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_singular raise LinAlgError("Singular matrix") numpy.linalg.LinAlgError: Singular matrix`

you really need to increase the stats to get 3 and 4 to work consistantly. For 3 I had to change it to 500, even thenif the asym or lambda's are similar it will still struggle. 

The error is in fitting the data and we cannot do much about that. In real life you would adjust the fitting range, we cannot do that as we have lost that data set.

2023-02-17 19:47 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/fit_functions/exp_decay.py
> +        :param decay_rate: the lambda value (decay  rate)
```suggestion
        :param decay_rate: the lambda value (decay rate)
```

2023-02-17 19:48 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/fit_functions/exp_decay.py
> +        return [1., 0.1]
I want to leave them here as the guess and bounds are going to change in the coming sprint

2023-02-17 19:48 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/fit_functions/exp_decay.py
> +        return [0., 0.001], [1., 20.]
same as above

2023-02-17 19:49 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/muon_exp_decay_main.py
> +    max_num = 4
I am planning to clean this up and refactor at some point as it is very similar to the quasi main files

2023-02-17 19:49 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/muon_exp_decay_main.py
> +    for N in range(1, max_num+1):
as part of the next sprint a lot of this will get simplified as lines 53 to 65 will become part of fitting

2023-02-17 19:50 UTC, AnthonyLim23 commented on src/quasielasticbayes/v2_python/muon_exp_decay_main.py
> +        (params, covar, fit) = scipy_curve_fit(x_data, sy, se,
they are left over from when the outputs were longer so split over multiple lines

2023-02-20 09:02 UTC, MialLewis commented on src/quasielasticbayes/v2_python/fit_functions/exp_decay.py
> +        return [1., 0.1]
Fair enoug

2023-02-20 09:03 UTC, MialLewis commented on test/muonexpdecay_test.py
> +    def test_two_decays(self):
Yes I installed as a developed and ran all the tests, `test_two_decays` output the warning.

2023-02-20 09:06 UTC, MialLewis commented
> > Not directly related to the code, and may be user error, but I've been playing around with the attached script and have the following observations [QuasiBayesMuon_3.txt](https://github.com/mantidproject/quasielasticbayes/files/10769396/QuasiBayesMuon_3.txt).
> > 
> > 1. Looking at the script output with `N=3` and `N=4` on line `66`, the `loglikelihood` does not indicate the correct value of N. This does not change when increase the number of MEvents through the `stats` variable on line `67`.
> > 2. The script crashed several times with 'N=2' and 'stats>100', though I can't replicate currently...:
> >    `Traceback (most recent call last):   File "C:\Repos\GitHub\Working Files\QuasiBayes Muon check\QuasiBayesMuon_2.py", line 77, in <module> (params, errors, new_x, fits, errors_fit) = muon_expdecay_main(sample,BG_type, start, end, params, errors)   File "src\quasielasticbayes\v2_python\muon_exp_decay_main.py", line 72, in quasielasticbayes.v2.MuonExpDecay.muon_expdecay_main results[prob_name] = [loglikelihood(len(sy), chi2,   File "src\quasielasticbayes\v2_python\log_likelihood.py", line 51, in quasielasticbayes.v2.log_likelihood.loglikelihood log_hess_det = log10_hessian_det(covar)   File "src\quasielasticbayes\v2_python\fit_engines\fit_utils.py", line 18, in quasielasticbayes.v2.fitting.fit_utils.log10_hessian_det hessian = np.linalg.inv(covar)   File "C:\Users\wym92549\AppData\Local\mambaforge\envs\quasielasticbayes-dev\lib\site-packages\numpy\linalg\linalg.py", line 551, in inv ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)   File "C:\Users\wym92549\AppData\Local\mambaforge\envs\quasielasticbayes-dev\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_singular raise LinAlgError("Singular matrix") numpy.linalg.LinAlgError: Singular matrix`
> 
> you really need to increase the stats to get 3 and 4 to work consistantly. For 3 I had to change it to 500, even thenif the asym or lambda's are similar it will still struggle.
> 
> The error is in fitting the data and we cannot do much about that. In real life you would adjust the fitting range, we cannot do that as we have lost that data set.

I'm happy that this issue is known, and satisfied with the reasoning.

2023-02-20 10:03 UTC, MialLewis approved these changes

2023-02-20 10:25 UTC, merged