Adding FFT tests
mantidproject/quasielasticbayes pull request #6
Opened 2022-02-25 13:37 UTC by AnthonyLim23

Since FFT's are a vital part of the analysis (being used many times). I have created a package so we can test the FFT code. I have written tests based on the combinations that are used in the rest of the code base (1,-1,-1 and 1, 1, 0 I got these using grep for FOUR2). 

This will also allow us to easily test any replacement system.

2022-03-09 14:42 UTC, martyngigg requested changes
It's good that we are starting to have isolated tests for various components. Just a couple of comments.

2022-03-09 14:42 UTC, martyngigg commented on quasielasticbayes/Four_main.f90
> +      OPEN(UNIT=11,FILE='C:\Users\BTR75544\work\f70.txt')
Can we remove the hardcoded file paths? This won't be able to execute anywhere else...

2022-03-09 14:42 UTC, martyngigg commented on quasielasticbayes/test/FFT_test.py
> +"""Characterization tests for QLres module"""
Can we remove the unused parts here?

2022-03-09 14:42 UTC, martyngigg commented on quasielasticbayes/test/FFT_test.py
> +    Characterization tests using inputs that have been accepted as correct.
Could we also update the comments here to be more relevant to the tests?

2022-03-09 14:42 UTC, martyngigg commented on quasielasticbayes/test/FFT_test.py
> +class FFTTest(unittest.TestCase):
Should we rename this `FourTest`? If we think it's not actually a true FFT then it might be best to just label exactly what we are testing.

2022-03-09 14:53 UTC, martyngigg commented on quasielasticbayes/test/FFT_test.py
> +        x = np.asarray([np.complex(0.0) for _ in range(4098)])
Can we also use as much built-in functionality from numpy as possible? This drops one loop and only leaves a list comprehension:
```
x = np.zeros(4098, dtype=complex)
nonzero_entries = 8
x[:nonzero_entries] = [complex(np.cos(i)+0.1,0.) for i in range(nonzero_entries)]
```

2022-03-11 12:14 UTC, AnthonyLim23 commented on quasielasticbayes/Four_main.f90
> +      OPEN(UNIT=11,FILE='C:\Users\BTR75544\work\f70.txt')
dont need this. It was some debugging that I forgot to remove

2022-03-11 12:14 UTC, AnthonyLim23 commented on quasielasticbayes/test/FFT_test.py
> +class FFTTest(unittest.TestCase):
yep

2022-03-14 09:07 UTC, martyngigg approved these changes
Thanks for making those changes. This looks good now.

2022-03-14 09:07 UTC, merged