Changed test to get correct path
mantidproject/quasielasticbayes pull request #8
Opened 2022-02-25 15:23 UTC by AnthonyLim23

The unit test had a hard coded path, which caused it to file for all but one machine. I have removed the path from the input json file, added a helper method for creating a path (one directory up from quasibayes) and updated the test to use it.

2022-02-28 13:53 UTC, martyngigg requested changes
Thanks for fixing this.

I've just got a request for a minor improvement for readability.

2022-02-28 13:53 UTC, martyngigg commented on quasielasticbayes/test/qlres_test.py
> +        inputs['wrks'] = add_path(inputs['wrks'])
From just reading this part I can't quite tell where this will end up without reading the implementation. Can I suggest that we use a temporary directory for these files? If not they'll get written and could get accidentally added to git.
Can we use [tempfile.NamedTemporaryDirectory](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) to create a directory in a context manager (`with`) and then pass that through to your new function?

2022-02-28 14:03 UTC, AnthonyLim23 commented on quasielasticbayes/test/qlres_test.py
> +        inputs['wrks'] = add_path(inputs['wrks'])
I will have a look into it

2022-03-09 14:58 UTC, martyngigg requested changes

2022-03-09 14:58 UTC, martyngigg commented on quasielasticbayes/test/qlres_test.py
> +        temp_dir = tempfile.TemporaryDirectory()
Thanks for looking at this. It's clearer what is going on here now.

Can I ask for one final change. TemporaryDirectory can be used as a context manager to ensure cleanup automatically without needing to use `.cleanup`. This has the advantage that if something throws an exception in the code that we weren't expecting and before hitting `.cleanup` then the directory will still be cleaned up. https://docs.python.org/3/library/tempfile.html#tempfile-examples shows an example of how to use it.

2022-03-11 13:43 UTC, martyngigg commented on quasielasticbayes/test/qlres_test.py
> +        #tmp_dir.cleanup() done on exiting the with statment
Thanks for this.

Can I be picky and ask we remove this commented code? I think from the outside someone would be unsure why it was left if it's not doing anything...

2022-03-11 14:45 UTC, AnthonyLim23 commented on quasielasticbayes/test/qlres_test.py
> +        #tmp_dir.cleanup() done on exiting the with statment
```suggestion
```

2022-03-11 14:49 UTC, martyngigg commented on quasielasticbayes/testing.py
> +    return os.path.join(file_path,'..',file_name)
This might be my Friday head but will this not put the files in the parent to the temporary directory we created?

2022-03-11 14:52 UTC, AnthonyLim23 commented on quasielasticbayes/testing.py
> +    return os.path.join(file_path,'..',file_name)
you are right. This is hang up from one of my earlier tests

2022-03-11 14:52 UTC, AnthonyLim23 commented on quasielasticbayes/testing.py
> +    return os.path.join(file_path,'..',file_name)
```suggestion
    return os.path.join(file_path, file_name)
```

2022-03-11 15:10 UTC, martyngigg approved these changes
Thanks for making the changes and this much improves the test so it is now portable.

2022-03-11 15:10 UTC, merged